### ISSUE TITLE
Adding wrong mover to a station

### ISSUE THREAD

**Issue by DanielPedrazzini** [Beckhoff-Switzerland/CHALET_Xts_Example#1]
Hello,
We noticed that after a enable -> disable -> enable or deleting all queue and adding movers to stations, that the wrong movers are added to a the stations.

In the picture below, I have try to add the mover 17 to the station 1 using the methode AddMoverToQueue. We can see on the online, that the station 1 has in the queue 0 the mover 16 instead of the 17.

Do you have any suggestion why this is appening ?

![CHALET_Xts_Example - Add wrong mover to station queue](https://github.com/Beckhoff-Switzerland/CHALET_Xts_Example/assets/161427730/7df6315d-af98-4dcd-a5af-4cd067a0b738)

**Comment by Andreas-BACH** [comment]
Thank your for reporting.
In my estimation, this is a display issue with TwinCat or the underlying Codesys. Here is an example with the variable "ipMover" of type interface "I_XTS_Mover". Properties marked in red are guaranteed and listed by the interface. The object "Sample_XTS_Large.PLC1.MAIN.aMover[19]" is only there for better diagnostics and is only available in the online view.
Unfortunately, the wrong instance is displayed in this online view. However, the red values from the property are correct. The function of the CHALET_XTS is therefore correct.
![image](https://github.com/Beckhoff-Switzerland/CHALET_Xts_Example/assets/143804651/5356e294-0d44-4ccd-a967-05e31ebf3ac5)

We will follow up on this point internally

Kind regards Andreas
